apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
   - ReadWriteMany
  storageClassName: efs-sc #Vai criar o PV dinamicamente a partir do storage class - usando o provisioner especificado.
  resources:
    requests:
      storage: 0.5Gi