kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com #Provisioner precisa ser instalado pelo control node.
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-056ab2665334ae1b1
  directoryPerms: "700"