apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: nfs
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.1.17
    path: /mnt/nfs
  storageClassName: local-storage-class
